name: Linux build

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Dependency install
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt install gcc-12 g++-12
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
        sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libglew-dev ninja-build
    - name: Build & install EssaGUI
      run: |
        ./install.sh
    # TODO: Add some tests.
