name: Linux build

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Dependency install
      run: sudo apt install libsfml-dev libglew-dev ninja-build
    - name: Build & install EssaGUI
      run: |
        ./install.sh
    # TODO: Add some tests.
